### PR TITLE
feat: support realtime toggle update via socket.io

### LINKED ISSUE #27: feat: java sdk integrate socketio client to receive realtime toggle update event

### PR DESCRIPTION
**Pull request by hezean**
resolves #27

### CODE REVIEW

**Comment by hezean** [comment]
awaiting for #29 to be merged

**Comment by SSebo** [comment]
Good Job, How about add a Test case to connecting `featureprobe.io` to make sure socketio connect success?

**Comment by hezean** [comment]
it was manually tested, imho it’s not a good idea to let ut depends on external resourcesBest regards,Zean HeSent from mobile device.On Dec 28, 2022, at 10:49, SSebo ***@***.***> wrote:﻿
Good Job, How about add a Test case to connecting featureprobe.io to make sure socketio connect success?

**Comment by SSebo** [comment]
> it was manually tested, imho it’s not a good idea to let ut depends on external resourcesBest regards,Zean HeSent from mobile device.On Dec 28, 2022, at 10:49, SSebo ***@***.***> wrote:﻿ Good Job, How about add a Test case to connecting featureprobe.io to make sure socketio connect success? —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

You are right, but it is better than no test. Rust SDK test this via an embed Server.
I have two ideas:
1. Treat it as an integration test, only run in github actions.
2. Embed js socketio server for test (better but more complex).

**Comment by gangb-tech** [comment]
Good, The stream feature should be independent. You can try to abstract a StreamSynchronizer to implement it.

**Comment by gangb-tech** [comment]
This request has been merged into #36

**Pull request closed without merging**
